# Base configs
baseurl: "https://randomwalker.org"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Raghavendra"
subtitle: "See the world through my eyes!"
author: "Raghavendra"
header:
 title: "Photography"
 subtitle: "Raghavendra"
footer:
 name: "Hey there, my name is Raghavendra"
 bio: "I am now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork this repo on github</a> ;)"
web_design: "AJ"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/sweetstark00"
  instagram: "https://www.instagram.com/raghavendram3"
  dribbble: "https://dribbble.com/"
  linkedin: "https://www.linkedin.com/in/raghavendra-meena/"
  github: "https://www.github.com/raghavendram3"
